[tools]
go-jsonnet = "latest"

[[watch_files]]
patterns = ["dotfiles/oh-my-posh.jsonnet"]
run = "jsonnet $MY_ZCOMET/dotfiles/oh-my-posh.jsonnet > $MY_ZCOMET/generated/oh-my-posh.json"

[tasks.generate]
description = "Generate completoins and init scripts"
run = "./setup/generate-source-cache.sh"

[tasks.post-merge]
run = "mise run generate"