[env]
#PROFILING = "1" # Enable profiling

[tools]
go-jsonnet = "latest"
# usage = "latest"

[tasks.generate]
alias = "githook-post-merge"
description = "Generate completoins and init scripts"
run = "./setup/generate-source-cache.sh"

[tasks.post-merge]
run = "mise run generate"

[tasks.sys-init]
description = "Initialize system. This is idempotent"
run = "cd $MISE_PROJECT_ROOT && ./setup/sys-init.sh"