#!/usr/bin/env bash

# Run post-merge mise task if it exists after a merge

set -e 

if mise run githook-post-merge --dry-run > /dev/null 2>&1 ; then
    echo "Running mise post-merge git hook..."
    mise run githook-post-merge
fi
